#! /usr/bin/env php

<?php

use Awps\NewCommand;
use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$app = new Application('AWPS Installer', '@package_version@');

$app->add(new NewCommand(new GuzzleHttp\Client()));

$app->run();
